# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Open Source', folder: 'pages', file: 'open_source.html'}
# - {name: 'Montreal', folder: 'pages', file: 'montreal.html'}
- {name: 'Mixing', folder: 'pages', file: 'mixing.html'}
- {name: 'Fun Links', folder: 'pages', file: 'fun_links.html'}
- {name: 'About Me', folder: 'pages', file: 'about_me.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/gab_downs'}
- {icon: 'facebook', link: 'https://www.facebook.com/gndowns'}
- {icon: 'instagram', link: 'https://instagram.com/the_gabe_gatsby'}
- {icon: 'envelope', link: 'mailto:gndowns@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
